class employee:
    def cal_tax(self):
        print("employee class")
class user:
    def cal_tax(self):
        print("user class")
class account:
    def cal_tax(self):
        print("account class")